### ISSUE TITLE
Windows "Cannot GET /" error

### ISSUE THREAD

**Issue by graphixillusion** [dosyago/DiskerNet#144]
Hi there. 

As the title says i'm getting this error with the just released version. I'm using a custom chrome build in a non-standard location so i'm using the CHROME_PATH env variable as instructed. When diskernet starts the browser i'll get the error "Cannot GET /" in the main page.

**Comment by crisdosyago** [comment]
Hi @graphixillusion If you let me know what you see from the console that might help me know more about this.

If you also set the DEBUG_22120 and VERBOSE_DEBUG_22120 env vars too and let me know I might be able to tell you more! 😃 

Have a good one, thanks for using 😸

**Comment by crisdosyago** [comment]
Hey I just confirmed this. THanks for reporting!

**Comment by crisdosyago** [comment]
Solved in [latest relaease](https://github.com/dosyago/DiskerNet/releases/tag/v2.9.0)

**Comment by graphixillusion** [comment]
@crisdosyago thank you for the quick fix, now it's working good. I would like to report another little cosmetic thing which appeared in the last build: when diskernet starts, these two lines appears at the beginning of the console view:

```
C:\snapshot\DiskerNet\build C:\snapshot\DiskerNet\build\diskernet.cjs
{ APP_ROOT: 'C:\\snapshot\\DiskerNet\\build' }
{ root: 'C:\\snapshot\\DiskerNet\\build' }
```
These lines weren't present in the previous build.

**Comment by crisdosyago** [comment]
@graphixillusion I’m sorry this will probably shock you, but I’m afraid i feel a little surprised and sad when I saw your follow up request.  So after I completed this quick critical fix you expect me to remove this cosmetic thing as well because it’s not to your liking? Maybe I’m okay with them there. But anyway how do you expect me to accomplish that?

Maybe I’d be happy to do the work for 30 USD. If you’d like this and this cosmetic fix is so important to you, and you value my time, you may pay my company here: https://buy.stripe.com/bIYeW6by1amTc6cbJR

**Comment by graphixillusion** [comment]
@crisdosyago i've reported becouse i believe it was a bug. If this is not the case it's ok. No need to be rude man, i was trying to help.

**Comment by crisdosyago** [comment]
So, @graphixillusion you know you don't know what's a bug or not or what's an improvement or not, in this context, right? It's my app, and you just want what you want for you, right? That's OK, it's not about that, I feel happy that you want to tell me what you want. What this is about is not that: but it *is* about how you say it, and _your expectations_. And yesterday when you added on another request after I'd quickly fixed the issue from your first report, I felt sad because it seemed like you thought I worked for you, and worked for you for free, and seems like you didn't value my time. And I really hope you would value my time, and understand that I do not work for you, and certainly not for free. I do this, all of this open-source work, for me: but, if you have a request and you put it respectfully with the understanding the boundaries of how that works, I'm so happy to know what you want. And maybe sometimes I'm gonna ask you to pay for it, and I hope you're okay with it. So, yesterday I put a price on it, because that's what this is about: time and respect. And yesterday it seems like you didn't value that. OK?

Also, you know that you can't apologize for how I feel, right? My feelings are my responsibility, not yours, they have nothing to do with you, and I'm perfectly comfortable with how I feel about this. If you don't like how I feel about this, that's your problem, nothing to do with me.  So when you do that--incorrectly try to apologize for someone else's feelings--it actually comes across as if you really feel you don't have anything to apologize for. Do you know that? Well, now you do. So, you know you can only apologize for your own actions, right? So, if you _do_ feel you have something to apologize for, then just say something like, "I'm sorry I did .... < whatever it is > ... ", instead of:

> usually, developers are happy with it when it happens. If this is not the case for you i'm sorry, i'll never report anything else.

Thank you! 

PS. Also, if you think you can act in a respectful way in future, I'm very happy to welcome you here with more great suggestions. After all you were the first person to notify me about the critical issue in the binary! That surely counts for something! 😄
